<?php //[STAMP] 6982986785f7268ad28639db22f4051e
namespace _generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use Codeception\Scenario;

trait FunctionalTesterActions
{
    /**
     * @return Scenario
     */
    abstract protected function getScenario();


}
